FROM golang:latest
ENV TESTERANTO_RUNTIME=golang
RUN mkdir -p /workspace/testeranto
RUN mkdir -p /workspace/testeranto/bundles
RUN mkdir -p /workspace/testeranto/metafiles
RUN mkdir -p /workspace/testeranto/reports
