supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
  cpu:
    - "current"
    - "x64"
    - "arm64"
  libc:
    - "current"
    - "glibc"
    - "musl"

# Clear the cache to avoid platform-specific issues
enableHardenedMode: false

# Don't use global cache which might have wrong platform packages
enableImmutableInstalls: false
