FROM node:20.19.4-alpine
# Install Golang
RUN apk add --update go
WORKDIR /workspace
COPY package*.json ./
RUN npm install --legacy-peer-deps
# Install ts-node to run TypeScript files
RUN npm install -g ts-node typescript
COPY . .
# Set up Go environment
ENV GOPATH=/go
ENV PATH=$PATH:/go/bin
RUN mkdir -p /go/src /go/bin && chmod -R 777 /go
RUN go mod download
