FROM node:20.19.4-alpine
# Install build tools for node-gyp and libxml2-utils for xmllint
RUN apk add --update make g++ linux-headers python3 libxml2-utils
WORKDIR /workspace
# Copy package files first to leverage Docker cache
COPY package*.json ./
RUN npm install --legacy-peer-deps
# Now copy the rest of the source code
COPY ./src ./src
# Run yarn tsc ./src

