FROM node:18-alpine
WORKDIR /workspace
COPY package*.json ./
# RUN npm install --legacy-peer-deps
# Install Docker SDK
# RUN npm install dockerode
# COPY . .
EXPOSE 8080
CMD ["npm", "run", "mothership"]
