FROM python:latest
ENV TESTERANTO_RUNTIME=python
RUN mkdir -p /workspace/testeranto
RUN mkdir -p /workspace/testeranto/bundles
RUN mkdir -p /workspace/testeranto/metafiles
RUN mkdir -p /workspace/testeranto/reports
