import fs from "fs";
import path from "path";
import esbuild from "esbuild";
import { IBuiltConfig } from "../../../Types";
import nodeConfiger from "./esbuild";

const testName = process.argv[2];

// run esbuild in watch mode using esbuildConfigs. Write to fs the bundle and metafile
async function startBundling(
  config: IBuiltConfig
) {
  console.log(`NODE BUILDER is now bundling:  ${testName}`);
  const n = nodeConfiger(config, testName);

  const bv = await esbuild.build(n);

  const metafilesDir =
    process.env.METAFILES_DIR || "/workspace/testeranto/metafiles/node";


  const metafilePath = path.join(metafilesDir, "allTests.json");
  if (bv.metafile) {
    const metafileWrapper = {
      errors: [],
      warnings: [],
      metafile: bv.metafile,
    };
    fs.writeFileSync(metafilePath, JSON.stringify(metafileWrapper, null, 2));
    console.log(`Node metafile written to ${metafilePath}`);
  } else {
    console.warn("No metafile generated by esbuild");
  }

  // THIS IS WRONG
  // fork(`testeranto/bundles/allTests/node/example/Calculator.test.mjs`, [
  //   config.httpPort.toString(),
  // ]);


}

async function main() {
  const config = (await import(`/workspace/${testName}`)).default;

  try {
    await startBundling(config);
  } catch (error) {
    console.error("NODE BUILDER: Error:", error);
    process.exit(1);
  }
}

main();
