/* eslint-disable @typescript-eslint/no-unused-vars */
import fs from "fs";
import path from "path";
import { fork } from "child_process";
import esbuild from "esbuild";
import { IBuiltConfig } from "../../../Types";
import nodeConfiger from "./esbuild";

const testName = process.argv[2];

// run esbuild in watch mode using esbuildConfigs. Write to fs the bundle and metafile
async function startBundling(
  config: IBuiltConfig
  // onMetafileChange: (esbuild: esbuild.BuildResult) => void
) {
  console.log(`NODE BUILDER is now bundling:  ${testName}`);
  const n = nodeConfiger(config, testName);

  const bv = await esbuild.build(n);

  // Write metafile in the same format as other runtimes
  const metafilesDir =
    process.env.METAFILES_DIR || "/workspace/testeranto/metafiles/node";

  // Ensure directory exists
  // if (!fs.existsSync(metafilesDir)) {
  //   fs.mkdirSync(metafilesDir, { recursive: true });
  // }

  const metafilePath = path.join(metafilesDir, "allTests.json");
  if (bv.metafile) {
    const metafileWrapper = {
      errors: [],
      warnings: [],
      metafile: bv.metafile,
    };
    fs.writeFileSync(metafilePath, JSON.stringify(metafileWrapper, null, 2));
    console.log(`Node metafile written to ${metafilePath}`);
  } else {
    console.warn("No metafile generated by esbuild");
  }

  fork(`testeranto/bundles/allTests/node/example/Calculator.test.mjs`, [
    config.httpPort.toString(),
  ]);

  // onMetafileChange(bv);
}

// run using user defined static analysis when the metafile changes
// async function startStaticAnalysis(esbuildResult: esbuild.BuildResult) {
//   console.log(`NODE BUILDER is now performing static analysis upon: `);
// }

// // run testeranto tests when the metafile changes
// async function startBddTests(esbuildResult: esbuild.BuildResult) {
//   console.log(`NODE BUILDER is now running testeranto tests:`);
// }

async function main() {
  const config = (await import(`/workspace/${testName}`)).default;

  try {
    await startBundling(config);
  } catch (error) {
    console.error("NODE BUILDER: Error:", error);
    process.exit(1);
  }
}

main();
