
import esbuild from "esbuild";

import {
  processMetafile
} from "../common";
import nodeConfiger from "./esbuild";
import { ITestconfigV2 } from "../../types";

console.log(`[NODE BUILDER] hello:  ${process.argv}`);

const projectConfigPath = process.argv[2];
const nodeConfigPath = process.argv[3];
const testName = process.argv[4];

console.log(`[NODE BUILDER] projectConfigPath:  ${projectConfigPath}`);
console.log(`[NODE BUILDER] nodeConfig:  ${nodeConfigPath}`);
console.log(`[NODE BUILDER] testName:  ${testName}`);

// run esbuild in watch mode using esbuildConfigs. Write to fs the bundle and metafile
async function startBundling(
  nodeConfigs: any,
  projectConfig: ITestconfigV2
) {
  console.log(`[NODE BUILDER] is now bundling:  ${testName}`);
  const n = nodeConfiger(nodeConfigs, testName, projectConfig);

  const buildResult = await esbuild.build(n);

  // const metafilesDir =
  //   process.env.METAFILES_DIR || "/workspace/testeranto/metafiles/node";
  if (buildResult.metafile) {
    await processMetafile(projectConfig, buildResult.metafile, 'node');

  } else {
    console.warn("No metafile generated by esbuild");
  }

}

async function main() {
  try {
    const nodeConfigs = (await import(nodeConfigPath)).default;
    const projectConfigs = (await import(projectConfigPath)).default;
    await startBundling(nodeConfigs, projectConfigs);
  } catch (error) {
    console.error("NODE BUILDER: Error importing config:", nodeConfigPath, error);
    console.error(error);
    process.exit(1);
  }
}

main();
