require 'json'
require 'fileutils'

puts "hello ruby builder", ARGV

# config_file_path is a ruby file
config_file_path = ARGV[0]
# Ensure the config file path is valid before requiring
if File.exist?(config_file_path)
  require config_file_path
else
  puts "Config file not found: #{config_file_path}"
  exit(1)
end

test_name = ARGV[1] || "allTests"

# Create necessary directories
input_files_path = "testeranto/bundles/allTests/ruby/example/Calculator.test.rb-inputFiles.json"
dummy_ruby_file_path = "testeranto/bundles/allTests/ruby/example/Calculator.test.rb"

# Ensure the directory exists
FileUtils.mkdir_p(File.dirname(input_files_path))
FileUtils.mkdir_p(File.dirname(dummy_ruby_file_path))

# Write input files JSON
input_files_content = {
  testName: test_name,
  configFile: config_file_path,
  timestamp: Time.now.to_i
}
File.write(input_files_path, JSON.pretty_generate(input_files_content))

# Write a dummy Ruby file that executes the actual test
dummy_ruby_content = <<-RUBY
#!/usr/bin/env ruby
# This file is generated by the ruby builder
# It executes the actual Calculator test

require 'json'

# Build the test resource configuration
config = {
  name: 'calculator-test',
  fs: '.',
  ports: [],
  timeout: 30000,
  retries: 0,
  environment: {}
}.to_json

# Execute the test file directly with the configuration
exec("ruby", "../../../../../example/Calculator-test.rb", config)
RUBY

File.write(dummy_ruby_file_path, dummy_ruby_content)
File.chmod(0755, dummy_ruby_file_path)

puts "Generated test files:"
puts "  - #{input_files_path}"
puts "  - #{dummy_ruby_file_path}"

# Now execute the generated test file
puts "Executing test..."
system("ruby #{dummy_ruby_file_path}")
exit($?.exitstatus)
