import {
  ClassyWhen,
  ClassyThen,
  ClassyGiven,
  ClassySuite,
  ClassyCheck,
} from "./../level2/TesterantoClasses";

export class TesterantoClassic<
  Klass,
  SuiteExtensions,
  GivenExtensions,
  WhenExtensions,
  ThenExtensions,
  CheckExtensions
> {
  constructorator: new (...any) => Klass;
  suiteOverides: Record<
    keyof SuiteExtensions,
    (feature: string) => ClassySuite<Klass>
  >;

  givenOverides: Record<
    keyof GivenExtensions,
    (
      feature: string,
      whens: ClassyWhen<Klass>[],
      thens: ClassyThen<Klass>[],
      ...xtraArgs
    ) => ClassyGiven<Klass>
  >;
  whenOverides: Record<keyof WhenExtensions, (any) => ClassyWhen<Klass>>;
  thenOverides: Record<keyof ThenExtensions, (any) => ClassyThen<Klass>>;
  checkOverides: Record<
    keyof CheckExtensions,
    (
      feature: string,
      callback: (whens, thens) => any,
      whens: ClassyWhen<Klass>[],
      thens: ClassyThen<Klass>[]
    ) => ClassyCheck<Klass>
  >;

  constructor(
    public readonly cc: new () => Klass,
    suiteOverides: Record<
      keyof SuiteExtensions,
      (feature: string) => ClassySuite<Klass>
    >,
    givenOverides: Record<
      keyof GivenExtensions,
      (
        feature: string,
        whens: ClassyWhen<Klass>[],
        thens: ClassyThen<Klass>[],
        ...xtraArgs
      ) => ClassyGiven<Klass>
    >,
    whenOverides: Record<keyof WhenExtensions, (c2: any) => ClassyWhen<Klass>>,
    thenOverides: Record<keyof ThenExtensions, (d2: any) => ClassyThen<Klass>>,
    checkOverides: Record<
      keyof CheckExtensions,
      (
        feature: string,
        callback: (whens, thens) => any,
        whens: ClassyWhen<Klass>[],
        thens: ClassyThen<Klass>[]
      ) => ClassyCheck<Klass>
    >
  ) {
    this.constructorator = cc;
    this.suiteOverides = suiteOverides;
    this.givenOverides = givenOverides;
    this.whenOverides = whenOverides;
    this.thenOverides = thenOverides;
    this.checkOverides = checkOverides;
  }

  Suites(): Record<keyof SuiteExtensions, (a: string) => ClassySuite<Klass>> {
    console.log("mark1", this.suiteOverides);
    return {
      ...this.suiteOverides,
    };
  }

  Given(): Record<
    keyof GivenExtensions,
    (
      feature: string,
      whens: ClassyWhen<Klass>[],
      thens: ClassyThen<Klass>[],
      ...xtraArgs
    ) => ClassyGiven<Klass>
  > {
    return {
      ...this.givenOverides,
    };
  }

  When(): Record<
    keyof WhenExtensions | keyof Klass,
    (any) => ClassyWhen<Klass>
  > {
    const objectdescription = Object.getOwnPropertyDescriptors(
      this.constructorator.prototype
    );

    let autogeneratedWhens = {};
    // Object.keys(objectdescription).forEach((k, ndx) => {
    //   autogeneratedWhens[k] = (...xArgs) =>
    //     new ClassyWhen<Klass>(`!${k}`, (y) => {
    //       return y[k](...xArgs);
    //     });
    // });

    /* @ts-ignore:next-line */
    return {
      ...autogeneratedWhens,
      ...this.whenOverides,
    };
  }

  Then(): Record<
    keyof ThenExtensions | keyof Klass,
    (any) => ClassyThen<Klass>
  > {
    let autogeneratedWhens = {};
    // Object.keys(
    //   Object.getOwnPropertyDescriptors(this.constructorator.prototype)
    // ).forEach(
    //   (publicMethod, ndx) =>
    //     (autogeneratedWhens[publicMethod] = (expected) =>
    //       new ClassyThen<Klass>(`!${publicMethod}`, (thing) =>
    //         assert.equal(thing[publicMethod](expected), expected)
    //       ))
    // );

    /* @ts-ignore:next-line */
    return {
      ...autogeneratedWhens,
      ...this.thenOverides,
    };
  }

  Checks(): Record<
    keyof CheckExtensions,
    (
      feature: string,
      callback: (whens, thens) => any,
      whens,
      thens
      // ...xtraArgs
    ) => ClassyCheck<Klass>
  > {
    return {
      ...this.checkOverides,
    };
  }
}
