
import esbuild from "esbuild";
import puppeteer from "puppeteer";
import { IBuiltConfig } from "../../../Types";
import configer from "./esbuild";
import { processMetafile } from "../common";
import * as fs from "fs";
import * as path from "path";

const configFilePath = "/workspace/testeranto/runtimes/web/web.js";  //path.join(process.cwd(), 'testeranto/runtimes/web/web.js'); //process.argv[2];
const testName = process.argv[3] || "allTests";

let browser: puppeteer.Browser;

async function startBundling(config: IBuiltConfig) {
  console.log(`[WEB BUILDER] is now bundling:  ${testName}`);

  // Validate config
  if (!config) {
    throw new Error('Config is undefined');
  }
  if (!config.buildDir) {
    console.warn('config.buildDir is undefined, using default');
    config.buildDir = '/workspace';
  }
  console.log(`Using build directory: ${config.buildDir}`);

  // Note: We no longer start Chrome here. The browser service runs separately.
  console.log("[WEB BUILDER] Using external browser service (browserless/chrome)");

  // Proceed with bundling
  const webConfig = configer(config, 'allTests');

  // Build the web bundle
  const buildResult = await esbuild.build(webConfig);

  if (buildResult.metafile) {
    await processMetafile(config, buildResult.metafile, 'web');

    // Create HTML files for each output
    const outputFiles = Object.keys(buildResult.metafile.outputs);
    for (const outputFile of outputFiles) {

      if (true) {
        const htmlPath = `testeranto/bundles/allTests/web/example/Calculator.test.ts.html`;

        // Ensure the directory exists
        await fs.promises.mkdir(path.dirname(htmlPath), { recursive: true });

        // Create HTML content
        const htmlContent = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Test Runner</title>
    </head>
    <body>
        <div id="root"></div>
        <script src="testeranto/bundles/allTests/web/example/Calculator.test.mjs"></script>
    </body>
    </html>`;

        await fs.promises.writeFile(htmlPath, htmlContent);
        console.log(`Created HTML file: ${htmlPath}`);
      }
    }
  } else {
    console.warn("No metafile generated by esbuild");
  }

  console.log("WEB BUILDER: Metafiles have been generated");

  // In dev mode, keep the process alive
  if ("dev" === "dev") {
    console.log(
      "WEB BUILDER: Running in dev mode, keeping builder alive..."
    );

    // Watch for changes to rebuild metafiles
    const ctx = await esbuild.context(webConfig);
    let { hosts, port } = await ctx.serve()
    console.log(
      `[WEB BUILDER]: esbuild server ${hosts}, ${port}`
    );

    // Keep the process alive
    process.on("SIGINT", async () => {
      console.log("WEB BUILDER: Shutting down...");
      process.exit(0);
    });

    // Keep alive
    await new Promise(() => {
      // This promise never resolves, keeping the process alive
    });
  }
}

async function main() {
  try {
    console.log(`[WEB BUILDER] Importing config from: ${configFilePath}`);
    const imported = await import(configFilePath);
    const config = imported.default;
    if (!config) {
      throw new Error(`Config not found in ${configFilePath}. Ensure the file exports a default object.`);
    }
    console.log('[WEB BUILDER] Config imported successfully:', Object.keys(config));
    await startBundling(config);
  } catch (error) {
    console.error("[WEB BUILDER]: Error importing config:", configFilePath, error);
    console.error(error);
    process.exit(1);
  }
}

main();
