import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import puppeteer from "puppeteer-core";
import { IBuiltConfig } from "../../../Types";
import configer from "./esbuild";

const testName = process.argv[2];
const mode = process.argv[3] || "dev";

let browser: puppeteer.Browser;

async function startChromeBrowser() {
  console.log("Starting Chrome browser via Puppeteer...");
  try {
    // Start Chrome with remote debugging enabled on port 9222
    // This matches the port exposed in the Docker Compose file
    browser = await puppeteer.launch({
      slowMo: 1,
      waitForInitialPage: false,
      executablePath: process.env.CHROMIUM_PATH || "/usr/bin/chromium-browser",
      defaultViewport: null,
      dumpio: true, // Enable to see browser logs in Docker
      args: [
        "--remote-debugging-port=9222",
        "--remote-debugging-address=0.0.0.0", // Allow connections from outside the container
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--disable-gpu",
        "--window-size=1920,1080",
        "--headless=new",
      ],
      headless: "new",
    });
    
    console.log("Chrome browser started with remote debugging on port 9222");
    console.log(`WebSocket endpoint: ${browser.wsEndpoint()}`);
    return browser;
  } catch (error) {
    throw new Error(`Chrome is not available: ${error.message}`);
  }
}

async function startBundling(config: IBuiltConfig) {
  const webConfig = configer(config, testName);

  // Build the web bundle
  const buildResult = await esbuild.build(webConfig);

  if (buildResult.errors.length > 0) {
    console.error("WEB BUILDER build errors:", buildResult.errors);
  }
  if (buildResult.warnings.length > 0) {
    console.warn("WEB BUILDER build warnings:", buildResult.warnings);
  }

  console.log(`WEB BUILDER build completed for ${testName}`);

  // Write metafile in the same format as other runtimes
  const metafilesDir =
    process.env.METAFILES_DIR || "/workspace/testeranto/metafiles/web";

  // Ensure directory exists
  if (!fs.existsSync(metafilesDir)) {
    fs.mkdirSync(metafilesDir, { recursive: true });
  }

  const generatedMetafilePath = path.join(metafilesDir, "allTests.json");
  if (buildResult.metafile) {
    const metafileWrapper = {
      errors: [],
      warnings: [],
      metafile: buildResult.metafile,
    };
    fs.writeFileSync(
      generatedMetafilePath,
      JSON.stringify(metafileWrapper, null, 2)
    );
    console.log(`Web metafile written to ${generatedMetafilePath}`);
  } else {
    console.warn("No metafile generated by esbuild");
  }

  await startChromeBrowser();

  console.log("WEB BUILDER: Chrome is now hosted and ready for test execution");
  console.log("WEB BUILDER: Metafiles have been generated");
  
  // In dev mode, keep the process alive to host Chrome
  if (mode === "dev") {
    console.log("WEB BUILDER: Running in dev mode, keeping Chrome instance alive...");
    
    // Watch for changes to rebuild metafiles
    console.log("WEB BUILDER: Setting up file watcher for rebuilds...");
    const ctx = await esbuild.context(webConfig);
    await ctx.watch();
    
    // Keep the process alive
    process.on("SIGINT", async () => {
      console.log("WEB BUILDER: Shutting down...");
      if (browser) await browser.close();
      process.exit(0);
    });
    
    // Keep alive
    await new Promise(() => {
      // This promise never resolves, keeping the process alive
    });
  }
}

async function main() {
  const configPathBase = `/workspace/${testName}`;

  const config = (await import(`/workspace/${testName}`)).default;

  try {
    await startBundling(config);

    // Keep the process alive in dev mode
    if (mode === "dev") {
      console.log("WEB BUILDER: Running in dev mode, keeping process alive...");
      // Keep process alive
      process.on("SIGINT", async () => {
        console.log("WEB BUILDER: Shutting down...");
        if (browser) await browser.close();
        process.exit(0);
      });
    }
  } catch (error) {
    console.error("WEB BUILDER: Error:", error);
    if (browser) await browser.close();
    process.exit(1);
  }
}

main();
