// Do not allow imports from outside the project (fs, exec, ws, etc)

import { IBuiltConfig, IRunTime } from "../../Types";
import { golangDockerComposeFile } from "../runtimes/golang/docker";
import { nodeDockerComposeFile } from "../runtimes/node/docker";
import { pythonDockerComposeFile } from "../runtimes/python/docker";
import { webDockerComposeFile } from "../runtimes/web/docker";

export type IService = any;


export interface IDockerComposeResult {
  exitCode: number;
  out: string;
  err: string;
  data: any;
}

export class DockerManager {

  cwd: string;
  composeFile: string;
  projectName: string

  constructor(composeFile: string, projectName: string) {
    this.cwd = process.cwd();
    this.composeFile = composeFile
    this.projectName = projectName
  }

  buildLogsHeader() {
    let header = `=== Docker Compose Build Logs ===\n`;
    header += `Started at: ${new Date().toISOString()}\n`;
    header += `Project: ${this.projectName}\n`;
    header += `Compose file: ${this.composeFile}\n`;
    header += "=".repeat(50) + "\n\n";
    return header;
  }

  BaseCompose(services: any) {
    return {
      services,
      volumes: {
        node_modules: {
          driver: "local",
        },
      },
      networks: {
        default: {
          name: "allTests_network",
        },
      },
    };
  }

  staticTestDockerComposeFile(config: IBuiltConfig, runtime: IRunTime, container_name: string) {
    return {
      build: {
        context: process.cwd(),
        dockerfile: `${config[runtime].dockerfile}`,
      },
      container_name,
      environment: {
        NODE_ENV: "production",
        ...config.env,
      },
      working_dir: "/workspace",
    }

  };

  bddTestDockerComposeFile(config: IBuiltConfig, runtime: IRunTime, container_name: string) {
    return {
      build: {
        context: process.cwd(),
        dockerfile: `${config[runtime].dockerfile}`,
      },
      container_name,
      environment: {
        NODE_ENV: "production",
        ...config.env,
      },
      working_dir: "/workspace",
    }

  };

  aiderDockerComposeFile(config: IBuiltConfig, runtime: IRunTime, container_name: string) {
    return {
      build: {
        context: process.cwd(),
        dockerfile: 'aider.Dockerfile',
      },
      container_name,
      environment: {
        NODE_ENV: "production",
        ...config.env,
      },
      working_dir: "/workspace",
      command: "aider"
    }

  };

  generateServices(
    config: IBuiltConfig,
    runtimes: IRunTime[],
  ): Record<string, any> {
    const services: IService = {};

    for (const runtime of runtimes) {
      if (runtime === "node") {
        services[`${runtime}-builder`] = nodeDockerComposeFile(config, 'allTests');
      } else if (runtime === "web") {
        services[`${runtime}-builder`] = webDockerComposeFile(config, 'allTests');
      } else if (runtime === "golang") {
        services[`${runtime}-builder`] = golangDockerComposeFile(config, 'allTests');
      } else if (runtime === "python") {
        services[`${runtime}-builder`] = pythonDockerComposeFile(config, 'allTests');
      } else {
        throw `unknown runtime ${runtime}`;
      }
      for (const test in config[runtime].tests) {


        const uid =
          `${runtime}-${test.toLowerCase().replaceAll("/", "_").replaceAll(".", "-")}`

        for (const [index, check] of config[runtime].checks.entries()) {
          const tuid = `${uid}-static-${index}`
          services[tuid] =
            this.staticTestDockerComposeFile(config, runtime, tuid);

        }
        services[`${uid}-bdd`] = this.bddTestDockerComposeFile(config, runtime, `${uid}-bdd`);
        services[`${uid}-aider`] = this.aiderDockerComposeFile(config, runtime, `${uid}-aider`);
      }
    }

    // Ensure all services use the same network configuration
    for (const serviceName in services) {
      services[serviceName].networks = ["default"];
    }

    return services;
  }

  autogenerateStamp(x: string) {
    return `# This file is autogenerated. Do not edit it directly
${x}
    `
  }

  public getUpCommand(): string {
    return `docker compose -f "${this.composeFile}" up -d`;
  }

  public getDownCommand(): string {
    return `docker compose -f "${this.composeFile}" down -v --remove-orphans`;
  }

  public getPsCommand(): string {
    return `docker compose -f "${this.composeFile}" ps`;
  }

  public getLogsCommand(serviceName?: string, tail: number = 100): string {
    const base = `docker compose -f "${this.composeFile}" logs --no-color --tail=${tail}`;
    return serviceName ? `${base} ${serviceName}` : base;
  }

  public getConfigServicesCommand(): string {
    return `docker compose -f "${this.composeFile}" config --services`;
  }

  public getBuildCommand(): string {
    return `docker compose -f "${this.composeFile}" build`;
  }

  public getStartCommand(): string {
    return `docker compose -f "${this.composeFile}" start`;
  }
}
