# This file is auto-generated by testeranto
# Signature: mixvh9fg
# It runs tests from: example/Calculator.pitono.test.py

import os
import sys

# Add the original entry point to the path
sys.path.insert(0, os.path.dirname(os.path.abspath("example/Calculator.pitono.test.py")))

# Import and run the tests
try:
    # Import the module
    module_name = os.path.basename("example/Calculator.pitono.test.py").replace('.py', '')
    module = __import__(module_name)
    
    # Run the tests if there's a main block
    if hasattr(module, 'main'):
        module.main()
    else:
        print(f"No main function found in {module_name}")
except Exception as e:
    print(f"Error running tests from example/Calculator.pitono.test.py: {e}")
    sys.exit(1)
